/**
 * Taboo card deck. Each card has one Guess Word and five Taboo (forbidden) words.
 * Family-friendly set for reunion play.
 */

export interface TabooCard {
  word: string;
  taboo: [string, string, string, string, string];
}

export const TABOO_CARDS: TabooCard[] = [
  { word: 'Birthday', taboo: ['Cake', 'Party', 'Candles', 'Age', 'Celebrate'] },
  { word: 'Beach', taboo: ['Sand', 'Ocean', 'Sun', 'Towel', 'Wave'] },
  { word: 'Pizza', taboo: ['Cheese', 'Pepperoni', 'Slice', 'Italian', 'Crust'] },
  { word: 'Snowman', taboo: ['Frosty', 'Winter', 'Carrot', 'Cold', 'Build'] },
  { word: 'Library', taboo: ['Books', 'Quiet', 'Read', 'Borrow', 'Shelves'] },
  { word: 'Campfire', taboo: ['Marshmallow', 'Wood', 'Flame', 'Smoke', 'Camping'] },
  { word: 'Dentist', taboo: ['Teeth', 'Drill', 'Cavity', 'Doctor', 'Floss'] },
  { word: 'Rainbow', taboo: ['Colors', 'Rain', 'Sky', 'Arc', 'Pot of Gold'] },
  { word: 'Elephant', taboo: ['Trunk', 'Big', 'Gray', 'Tusks', 'Africa'] },
  { word: 'Basketball', taboo: ['Hoop', 'Dribble', 'Court', 'NBA', 'Shoot'] },
  { word: 'Umbrella', taboo: ['Rain', 'Wet', 'Open', 'Handle', 'Cover'] },
  { word: 'Popcorn', taboo: ['Movie', 'Butter', 'Kernel', 'Pop', 'Snack'] },
  { word: 'Astronaut', taboo: ['Space', 'NASA', 'Rocket', 'Moon', 'Suit'] },
  { word: 'Piano', taboo: ['Keys', 'Music', 'Play', 'Instrument', 'Black and White'] },
  { word: 'Sandwich', taboo: ['Bread', 'Lunch', 'Meat', 'Peanut Butter', 'Sub'] },
  { word: 'Firefighter', taboo: ['Fire', 'Truck', 'Hose', 'Ladder', 'Rescue'] },
  { word: 'Roller Coaster', taboo: ['Ride', 'Amusement Park', 'Fast', 'Loop', 'Scream'] },
  { word: 'Toothbrush', taboo: ['Teeth', 'Paste', 'Clean', 'Bristles', 'Mouth'] },
  { word: 'Kangaroo', taboo: ['Australia', 'Hop', 'Pouch', 'Joey', 'Jump'] },
  { word: 'Chocolate', taboo: ['Candy', 'Sweet', 'Brown', 'Cocoa', 'Bar'] },
  { word: 'Airplane', taboo: ['Fly', 'Pilot', 'Wings', 'Airport', 'Sky'] },
  { word: 'Vampire', taboo: ['Blood', 'Dracula', 'Fangs', 'Bat', 'Bite'] },
  { word: 'Guitar', taboo: ['Strings', 'Play', 'Music', 'Rock', 'Strum'] },
  { word: 'Bowling', taboo: ['Pins', 'Strike', 'Ball', 'Alley', 'Roll'] },
  { word: 'Pancake', taboo: ['Syrup', 'Breakfast', 'Flip', 'Flat', 'Batter'] },
  { word: 'Spider', taboo: ['Web', 'Eight', 'Legs', 'Insect', 'Crawl'] },
  { word: 'Sunburn', taboo: ['Red', 'Beach', 'Lotion', 'Skin', 'Hot'] },
  { word: 'Wedding', taboo: ['Bride', 'Groom', 'Marriage', 'Ring', 'Dress'] },
  { word: 'Refrigerator', taboo: ['Cold', 'Food', 'Kitchen', 'Freezer', 'Ice'] },
  { word: 'Skateboard', taboo: ['Wheels', 'Ride', 'Trick', 'Ramp', 'Deck'] },
  { word: 'Cowboy', taboo: ['Horse', 'Hat', 'West', 'Lasso', 'Boots'] },
  { word: 'Igloo', taboo: ['Ice', 'Eskimo', 'Cold', 'House', 'Snow'] },
  { word: 'Lemonade', taboo: ['Drink', 'Sour', 'Stand', 'Yellow', 'Summer'] },
  { word: 'Pirate', taboo: ['Ship', 'Treasure', 'Eye Patch', 'Parrot', 'Arr'] },
  { word: 'Trampoline', taboo: ['Jump', 'Bounce', 'Springs', 'Backyard', 'Flip'] },
  { word: 'Volcano', taboo: ['Lava', 'Erupt', 'Mountain', 'Hot', 'Ash'] },
  { word: 'Waffle', taboo: ['Breakfast', 'Syrup', 'Squares', 'Iron', 'Pancake'] },
  { word: 'Zookeeper', taboo: ['Animals', 'Cage', 'Feed', 'Zoo', 'Lion'] },
  { word: 'Fireworks', taboo: ['Fourth of July', 'Explode', 'Sky', 'Boom', 'Colors'] },
  { word: 'Mermaid', taboo: ['Fish', 'Tail', 'Ocean', 'Ariel', 'Swim'] },
  { word: 'Microwave', taboo: ['Heat', 'Oven', 'Popcorn', 'Kitchen', 'Minutes'] },
  { word: 'Ballet', taboo: ['Dance', 'Tutu', 'Toes', 'Swan', 'Graceful'] },
  { word: 'Hamburger', taboo: ['Bun', 'Beef', 'Fries', 'McDonald’s', 'Patty'] },
  { word: 'Scarecrow', taboo: ['Birds', 'Field', 'Straw', 'Farm', 'Corn'] },
  { word: 'Submarine', taboo: ['Underwater', 'Ship', 'Ocean', 'Navy', 'Periscope'] },
  { word: 'Tornado', taboo: ['Wind', 'Storm', 'Spin', 'Twister', 'Funnel'] },
  { word: 'Giraffe', taboo: ['Neck', 'Tall', 'Spots', 'Africa', 'Animal'] },
  { word: 'Karate', taboo: ['Kick', 'Belt', 'Chop', 'Martial Arts', 'Punch'] },
  { word: 'Lighthouse', taboo: ['Ocean', 'Light', 'Ships', 'Tower', 'Coast'] },
  { word: 'Marshmallow', taboo: ['Campfire', 'Roast', 'White', 'Soft', 'S’more'] },
  { word: 'Ninja', taboo: ['Sword', 'Sneak', 'Black', 'Japan', 'Turtle'] },
  { word: 'Octopus', taboo: ['Eight', 'Tentacles', 'Ocean', 'Ink', 'Arms'] },
  { word: 'Parachute', taboo: ['Jump', 'Plane', 'Sky', 'Fall', 'Open'] },
  { word: 'Quicksand', taboo: ['Sink', 'Stuck', 'Sand', 'Jungle', 'Trap'] },
  { word: 'Robot', taboo: ['Machine', 'Metal', 'Beep', 'Computer', 'Future'] },
  { word: 'Sledding', taboo: ['Snow', 'Hill', 'Winter', 'Slide', 'Downhill'] },
  { word: 'Telescope', taboo: ['Stars', 'Look', 'Space', 'Lens', 'Astronomy'] },
  { word: 'Unicorn', taboo: ['Horn', 'Horse', 'Magic', 'Rainbow', 'Mythical'] },
  { word: 'Vacuum', taboo: ['Clean', 'Carpet', 'Suck', 'Dirt', 'Floor'] },
  { word: 'Waterfall', taboo: ['River', 'Niagara', 'Splash', 'Rocks', 'Flow'] },
  { word: 'X-ray', taboo: ['Bones', 'Doctor', 'Picture', 'Hospital', 'See Through'] },
  { word: 'Yo-yo', taboo: ['String', 'Up and Down', 'Toy', 'Spin', 'Trick'] },
  { word: 'Zipper', taboo: ['Jacket', 'Pants', 'Up', 'Teeth', 'Close'] },
  { word: 'Alarm Clock', taboo: ['Wake', 'Morning', 'Ring', 'Snooze', 'Time'] },
  { word: 'Babysitter', taboo: ['Kids', 'Watch', 'Parents', 'Pay', 'Night'] },
  { word: 'Cactus', taboo: ['Desert', 'Prickly', 'Needles', 'Green', 'Plant'] },
  { word: 'Dinosaur', taboo: ['Extinct', 'T-Rex', 'Fossil', 'Jurassic', 'Reptile'] },
  { word: 'Earthquake', taboo: ['Shake', 'Ground', 'Fault', 'Richter', 'Tremor'] },
  { word: 'Ferris Wheel', taboo: ['Ride', 'Carnival', 'Circle', 'Tall', 'Seats'] },
  { word: 'Garage Sale', taboo: ['Sell', 'Yard', 'Stuff', 'Cheap', 'Saturday'] },
  { word: 'Hiccups', taboo: ['Scare', 'Water', 'Breath', 'Sound', 'Stop'] },
  { word: 'Ice Cream', taboo: ['Cone', 'Cold', 'Scoop', 'Flavor', 'Dessert'] },
  { word: 'Jellyfish', taboo: ['Sting', 'Ocean', 'Tentacles', 'Float', 'Clear'] },
  { word: 'Ketchup', taboo: ['Tomato', 'Fries', 'Red', 'Mustard', 'Bottle'] },
  { word: 'Lawn Mower', taboo: ['Grass', 'Cut', 'Yard', 'Push', 'Engine'] },
  { word: 'Magician', taboo: ['Trick', 'Rabbit', 'Hat', 'Wand', 'Abracadabra'] },
  { word: 'Nightmare', taboo: ['Dream', 'Scary', 'Sleep', 'Wake', 'Bad'] },
  { word: 'Orchestra', taboo: ['Music', 'Instruments', 'Conductor', 'Symphony', 'Violin'] },
  { word: 'Penguin', taboo: ['Antarctica', 'Bird', 'Waddle', 'Tuxedo', 'Ice'] },
  { word: 'Quilt', taboo: ['Blanket', 'Sew', 'Patches', 'Bed', 'Grandma'] },
  { word: 'Recess', taboo: ['School', 'Play', 'Break', 'Playground', 'Kids'] },
  { word: 'Seatbelt', taboo: ['Car', 'Safety', 'Buckle', 'Strap', 'Click'] },
  { word: 'Treehouse', taboo: ['Climb', 'Kids', 'Wood', 'Backyard', 'Ladder'] },
  { word: 'Uniform', taboo: ['Clothes', 'School', 'Wear', 'Same', 'Team'] },
  { word: 'Ventriloquist', taboo: ['Dummy', 'Voice', 'Puppet', 'Mouth', 'Talk'] },
  { word: 'Windmill', taboo: ['Wind', 'Blades', 'Spin', 'Holland', 'Farm'] },
  { word: 'Yearbook', taboo: ['School', 'Photos', 'Sign', 'Memories', 'Graduation'] },
  { word: 'Aquarium', taboo: ['Fish', 'Tank', 'Water', 'Glass', 'Visit'] },
  { word: 'Bubble Gum', taboo: ['Chew', 'Blow', 'Pink', 'Sticky', 'Pop'] },
  { word: 'Carpool', taboo: ['Drive', 'Share', 'Ride', 'Work', 'Lane'] },
  { word: 'Detective', taboo: ['Clues', 'Mystery', 'Solve', 'Sherlock', 'Case'] },
  { word: 'Escalator', taboo: ['Stairs', 'Moving', 'Mall', 'Up', 'Ride'] },
  { word: 'Fortune Cookie', taboo: ['Chinese', 'Message', 'Paper', 'Crack', 'Lucky'] },
  { word: 'Goosebumps', taboo: ['Cold', 'Scared', 'Skin', 'Chills', 'Arms'] },
  { word: 'Hopscotch', taboo: ['Jump', 'Chalk', 'Sidewalk', 'Squares', 'Game'] },
  { word: 'Inchworm', taboo: ['Crawl', 'Small', 'Measure', 'Green', 'Bug'] },
  { word: 'Juggler', taboo: ['Balls', 'Throw', 'Catch', 'Circus', 'Air'] },
  { word: 'Kayak', taboo: ['Paddle', 'Boat', 'River', 'Water', 'Canoe'] },
  { word: 'Leprechaun', taboo: ['Irish', 'Gold', 'Green', 'Lucky', 'Rainbow'] },
  { word: 'Mustache', taboo: ['Lip', 'Hair', 'Face', 'Shave', 'Beard'] },
  { word: 'Nest', taboo: ['Bird', 'Eggs', 'Tree', 'Twigs', 'Build'] },
  { word: 'Overalls', taboo: ['Pants', 'Straps', 'Farmer', 'Denim', 'Wear'] },
  { word: 'Puzzle', taboo: ['Pieces', 'Fit', 'Picture', 'Jigsaw', 'Solve'] },
  { word: 'Quarterback', taboo: ['Football', 'Throw', 'Pass', 'Team', 'Huddle'] },
  { word: 'Raccoon', taboo: ['Mask', 'Trash', 'Night', 'Animal', 'Stripes'] },
  { word: 'Snorkel', taboo: ['Breathe', 'Underwater', 'Mask', 'Tube', 'Swim'] },
  { word: 'Tugboat', taboo: ['Pull', 'Ship', 'Small', 'Harbor', 'Water'] },
  { word: 'Applause', taboo: ['Clap', 'Hands', 'Audience', 'Cheer', 'Bravo'] },
  { word: 'Backpack', taboo: ['School', 'Carry', 'Shoulders', 'Books', 'Bag'] },
  { word: 'Chameleon', taboo: ['Color', 'Change', 'Lizard', 'Blend', 'Camouflage'] },
  { word: 'Doughnut', taboo: ['Hole', 'Glazed', 'Sprinkles', 'Fried', 'Sweet'] },
  { word: 'Eclipse', taboo: ['Sun', 'Moon', 'Dark', 'Shadow', 'Sky'] },
  { word: 'Flamingo', taboo: ['Pink', 'Bird', 'One Leg', 'Stand', 'Lawn'] },
  { word: 'Gingerbread', taboo: ['Cookie', 'House', 'Man', 'Christmas', 'Candy'] },
  { word: 'Hammock', taboo: ['Swing', 'Trees', 'Relax', 'Nap', 'Rope'] },
  { word: 'Iceberg', taboo: ['Titanic', 'Ocean', 'Cold', 'Float', 'Tip'] },
  { word: 'Jackpot', taboo: ['Win', 'Money', 'Lottery', 'Slot Machine', 'Prize'] },
  { word: 'Kite', taboo: ['Fly', 'String', 'Wind', 'Sky', 'Tail'] },
  { word: 'Limousine', taboo: ['Long', 'Car', 'Driver', 'Fancy', 'Prom'] },
  { word: 'Muffin', taboo: ['Blueberry', 'Bake', 'Breakfast', 'Cupcake', 'Top'] },
  { word: 'Newspaper', taboo: ['Read', 'Headlines', 'Daily', 'Print', 'Deliver'] },
  { word: 'Ostrich', taboo: ['Bird', 'Big', 'Run', 'Head in Sand', 'Egg'] },
  { word: 'Pillow Fight', taboo: ['Hit', 'Feathers', 'Bed', 'Sleepover', 'Soft'] },
  { word: 'Quicksilver', taboo: ['Mercury', 'Fast', 'Metal', 'Liquid', 'Silver'] },
  { word: 'Rocking Chair', taboo: ['Sit', 'Back and Forth', 'Porch', 'Grandma', 'Wood'] },
  { word: 'Stethoscope', taboo: ['Doctor', 'Heart', 'Listen', 'Chest', 'Nurse'] },
  { word: 'Tricycle', taboo: ['Three', 'Wheels', 'Ride', 'Kid', 'Pedal'] },
  { word: 'Underdog', taboo: ['Win', 'Lose', 'Expected', 'Favorite', 'Root'] },
  { word: 'Violin', taboo: ['Strings', 'Bow', 'Music', 'Fiddle', 'Orchestra'] },
  { word: 'Wheelbarrow', taboo: ['Push', 'Garden', 'Wheel', 'Carry', 'Dirt'] },
  { word: 'Sunflower', taboo: ['Yellow', 'Seeds', 'Tall', 'Garden', 'Sun'] },
  { word: 'Time Machine', taboo: ['Travel', 'Past', 'Future', 'Back', 'Invention'] },
  { word: 'Superhero', taboo: ['Cape', 'Powers', 'Save', 'Comic', 'Villain'] },
  { word: 'Slippers', taboo: ['Feet', 'Cozy', 'House', 'Shoes', 'Wear'] },
  { word: 'Photograph', taboo: ['Camera', 'Picture', 'Smile', 'Album', 'Take'] },
  { word: 'Opera', taboo: ['Sing', 'Music', 'Stage', 'Loud', 'Fat Lady'] },
  { word: 'Mosquito', taboo: ['Bite', 'Itch', 'Bug', 'Blood', 'Buzz'] },
  { word: 'Lifeguard', taboo: ['Pool', 'Save', 'Whistle', 'Beach', 'Swim'] },
  { word: 'Karaoke', taboo: ['Sing', 'Microphone', 'Songs', 'Words', 'Screen'] },
  { word: 'Homework', taboo: ['School', 'Assignment', 'Teacher', 'Study', 'Due'] },
  { word: 'Grasshopper', taboo: ['Jump', 'Green', 'Insect', 'Legs', 'Field'] },
  { word: 'Fishing Rod', taboo: ['Catch', 'Reel', 'Bait', 'Hook', 'Lake'] },
  { word: 'Escalate', taboo: ['Increase', 'Rise', 'Grow', 'Up', 'Worse'] },
  { word: 'Drum', taboo: ['Beat', 'Sticks', 'Band', 'Hit', 'Rhythm'] },
  { word: 'Compass', taboo: ['North', 'Direction', 'Needle', 'Navigate', 'Lost'] },
  { word: 'Blender', taboo: ['Smoothie', 'Mix', 'Kitchen', 'Blade', 'Juice'] },
  { word: 'Avalanche', taboo: ['Snow', 'Mountain', 'Slide', 'Bury', 'Ski'] },

  // ---- Family dictionary cards ----
  { word: 'Save', taboo: ['Money', 'Time', 'Later', 'Bank', 'Keep'] },
  { word: 'Pay', taboo: ['Money', 'Price', 'Buy', 'Sell', 'Cash'] },
  { word: 'Head', taboo: ['Top', 'Face', 'Round', 'Hair', 'Brain'] },
  { word: 'Word', taboo: ['Write', 'Sentence', 'Letter', 'Speak', 'Say'] },
  { word: 'Storm', taboo: ['Lightning', 'Thunder', 'Hurricane', 'Weather', 'Rain'] },
  { word: 'Museum', taboo: ['Art', 'History', 'Quiet', 'National', 'Exhibit'] },
  { word: 'Company', taboo: ['Business', 'Corporation', 'Work', 'Employer', 'Office'] },
  { word: 'Speak', taboo: ['Talk', 'Language', 'English', 'Mouth', 'Say'] },
  { word: 'War', taboo: ['Violence', 'Army', 'World', 'Weapons', 'Battle'] },
  { word: 'Team', taboo: ['Sport', 'Play', 'National', 'Together', 'Group'] },
  { word: 'Married', taboo: ['Single', 'Husband', 'Wife', 'Wedding', 'Ring'] },
  { word: 'Star', taboo: ['Sun', 'Bright', 'Yellow', 'Night', 'Sky'] },
  { word: 'Army', taboo: ['Soldiers', 'War', 'Fight', 'Guns', 'Military'] },
  { word: 'Invite', taboo: ['Guest', 'Attend', 'Party', 'Wedding', 'Ask'] },
  { word: 'Busy', taboo: ['Work', 'Time', 'School', 'Rush', 'Schedule'] },
  { word: 'Sky', taboo: ['Blue', 'Clouds', 'Birds', 'Sun', 'Above'] },
  { word: 'Teacher', taboo: ['Student', 'Class', 'Explain', 'School', 'Lesson'] },
  { word: 'Poor', taboo: ['Rich', 'Money', 'Buy', 'Pay', 'Broke'] },
  { word: 'Blood', taboo: ['Red', 'Cut', 'Vein', 'Heart', 'Donate'] },
  { word: 'Discover', taboo: ['Scientist', 'Research', 'Find', 'New', 'Explore'] },
  { word: 'Outside', taboo: ['Inside', 'Roof', 'Park', 'Yard', 'Door'] },
  { word: 'Lawyer', taboo: ['Court', 'Sue', 'Trial', 'Judge', 'Attorney'] },
  { word: 'Nurse', taboo: ['Care', 'Patient', 'Sick', 'Hospital', 'Doctor'] },
  { word: 'Camera', taboo: ['Picture', 'Take', 'Digital', 'Video', 'Lens'] },
  { word: 'Heavy', taboo: ['Light', 'Metal', 'Weight', 'Lift', 'Pounds'] },
  { word: 'Skin', taboo: ['Cover', 'Color', 'Outside', 'Protect', 'Body'] },
  { word: 'Coach', taboo: ['Team', 'Player', 'Leader', 'Sport', 'Train'] },
  { word: 'Travel', taboo: ['Vacation', 'Visit', 'Plane', 'Country', 'Trip'] },
  { word: 'Weekend', taboo: ['Work', 'Free', 'Saturday', 'Sunday', 'Friday'] },
  { word: 'Mountain', taboo: ['Climb', 'Everest', 'Tall', 'Snow', 'Peak'] },
  { word: 'Celebrate', taboo: ['Party', 'Birthday', 'Anniversary', 'Friends', 'Cheer'] },
  { word: 'Desert', taboo: ['Dry', 'Hot', 'Sahara', 'Sand', 'Cactus'] },
  { word: 'Home', taboo: ['Live', 'House', 'Sleep', 'Family', 'Address'] },
  { word: 'Wine', taboo: ['Grapes', 'White', 'Red', 'Alcohol', 'Bottle'] },
  { word: 'Fire', taboo: ['Hot', 'Red', 'Fighter', 'Camping', 'Burn'] },
  { word: 'Flower', taboo: ['Rose', 'Funeral', 'Wedding', 'Garden', 'Petals'] },
  { word: 'Border', taboo: ['Between', 'Country', 'Limit', 'Line', 'Edge'] },
  { word: 'Fun', taboo: ['Enjoy', 'Activity', 'Game', 'Time', 'Play'] },
  { word: 'Cigarette', taboo: ['Smoke', 'Marlboro', 'Cancer', 'Habit', 'Tobacco'] },
  { word: 'Private', taboo: ['Personal', 'Secret', 'Information', 'Public', 'Hidden'] },
  { word: 'Wake Up', taboo: ['Morning', 'Bed', 'Early', 'Get Up', 'Alarm'] },
  { word: 'Weak', taboo: ['Strong', 'Muscle', 'Small', 'Strength', 'Power'] },
  { word: 'Dark', taboo: ['Light', 'Night', 'See', 'Sleep', 'Black'] },
  { word: 'Knife', taboo: ['Fork', 'Spoon', 'Cut', 'Sharp', 'Blade'] },
  { word: 'Kiss', taboo: ['Lips', 'Love', 'Cheek', 'Romantic', 'Hug'] },
  { word: 'Smoke', taboo: ['Gray', 'Burn', 'Cook', 'Fire', 'Chimney'] },
  { word: 'Bear', taboo: ['Woods', 'Brown', 'Black', 'Animal', 'Grizzly'] },
  { word: 'Professor', taboo: ['Teacher', 'University', 'Students', 'Class', 'College'] },
  { word: 'Dirty', taboo: ['Clean', 'Clothes', 'Shower', 'Soap', 'Mud'] },
  { word: 'Raw', taboo: ['Sushi', 'Cook', 'Eat', 'Meat', 'Fresh'] },
  { word: 'Stairs', taboo: ['Up', 'Down', 'Climb', 'House', 'Steps'] },
  { word: 'Blanket', taboo: ['Warm', 'Bed', 'Sheet', 'Cover', 'Cozy'] },
  { word: 'Dessert', taboo: ['Cake', 'Pie', 'Sweet', 'Cookie', 'Ice Cream'] },
  { word: 'T-Shirt', taboo: ['Wear', 'Casual', 'Jeans', 'White', 'Cotton'] },
  { word: 'Smart', taboo: ['Intelligent', 'Nerd', 'Brain', 'Knowledge', 'Clever'] },
  { word: 'King', taboo: ['Queen', 'Prince', 'Leader', 'Country', 'Crown'] },
  { word: 'Dance', taboo: ['Move', 'Music', 'Song', 'Ballet', 'Party'] },
  { word: 'Send', taboo: ['Email', 'Letter', 'Receive', 'Package', 'Mail'] },
  { word: 'Late', taboo: ['Early', 'Meeting', 'Time', 'Arrive', 'Tardy'] },
  { word: 'Religion', taboo: ['God', 'Belief', 'Culture', 'Faith', 'Church'] },
  { word: 'Couch', taboo: ['Sit', 'Living Room', 'TV', 'Relax', 'Sofa'] },
  { word: 'Finish', taboo: ['Stop', 'Start', 'Done', 'Task', 'End'] },
  { word: 'Apple', taboo: ['Red', 'Fruit', 'Pie', 'Eat', 'Core'] },
  { word: 'Study', taboo: ['Test', 'Quiz', 'Remember', 'School', 'Books'] },
  { word: 'Bus', taboo: ['Ride', 'Transportation', 'Stop', 'Public', 'School'] },
  { word: 'Weather', taboo: ['Rain', 'Snow', 'Sun', 'Forecast', 'Temperature'] },
  { word: 'Sick', taboo: ['Well', 'Cold', 'Flu', 'Doctor', 'Ill'] },
  { word: 'Vacation', taboo: ['Trip', 'Work', 'Travel', 'Beach', 'Holiday'] },
  { word: 'Gym', taboo: ['Weights', 'Work Out', 'Sweat', 'Exercise', 'Fitness'] },
  { word: 'Window', taboo: ['Glass', 'Door', 'Outside', 'Open', 'Curtains'] },
  { word: 'Cheese', taboo: ['Milk', 'White', 'Pizza', 'Sandwich', 'Cheddar'] },
  { word: 'Swim', taboo: ['Beach', 'Water', 'Bathing Suit', 'Exercise', 'Pool'] },

  // ---- New cards in the same everyday-word style ----
  { word: 'Doctor', taboo: ['Nurse', 'Hospital', 'Sick', 'Medicine', 'Patient'] },
  { word: 'Hospital', taboo: ['Doctor', 'Nurse', 'Emergency', 'Bed', 'Ambulance'] },
  { word: 'Money', taboo: ['Cash', 'Dollars', 'Pay', 'Rich', 'Wallet'] },
  { word: 'Kitchen', taboo: ['Cook', 'Food', 'Stove', 'Sink', 'House'] },
  { word: 'Winter', taboo: ['Cold', 'Snow', 'Season', 'Coat', 'December'] },
  { word: 'Summer', taboo: ['Hot', 'Sun', 'Season', 'Vacation', 'June'] },
  { word: 'Breakfast', taboo: ['Morning', 'Eggs', 'Cereal', 'Meal', 'Eat'] },
  { word: 'Sleep', taboo: ['Bed', 'Night', 'Dream', 'Tired', 'Eyes'] },
  { word: 'Run', taboo: ['Fast', 'Legs', 'Race', 'Jog', 'Exercise'] },
  { word: 'Cold', taboo: ['Hot', 'Ice', 'Winter', 'Temperature', 'Freezing'] },
  { word: 'Rain', taboo: ['Water', 'Umbrella', 'Wet', 'Clouds', 'Storm'] },
  { word: 'Music', taboo: ['Song', 'Listen', 'Notes', 'Band', 'Radio'] },
  { word: 'Book', taboo: ['Read', 'Pages', 'Library', 'Story', 'Author'] },
  { word: 'Phone', taboo: ['Call', 'Talk', 'Cell', 'Ring', 'Text'] },
  { word: 'Computer', taboo: ['Keyboard', 'Screen', 'Internet', 'Type', 'Laptop'] },
  { word: 'Car', taboo: ['Drive', 'Wheels', 'Road', 'Engine', 'Vehicle'] },
  { word: 'Shoes', taboo: ['Feet', 'Wear', 'Socks', 'Walk', 'Laces'] },
  { word: 'Hungry', taboo: ['Food', 'Eat', 'Stomach', 'Full', 'Starving'] },
  { word: 'Tired', taboo: ['Sleep', 'Yawn', 'Rest', 'Energy', 'Exhausted'] },
  { word: 'Happy', taboo: ['Sad', 'Smile', 'Joy', 'Glad', 'Feeling'] },
  { word: 'Angry', taboo: ['Mad', 'Upset', 'Yell', 'Red', 'Emotion'] },
  { word: 'Scared', taboo: ['Afraid', 'Fear', 'Scream', 'Monster', 'Dark'] },
  { word: 'Tall', taboo: ['Short', 'Height', 'Basketball', 'Giant', 'Big'] },
  { word: 'Fast', taboo: ['Slow', 'Quick', 'Speed', 'Run', 'Race'] },
  { word: 'Old', taboo: ['Young', 'Age', 'Grandparent', 'Antique', 'New'] },
  { word: 'Loud', taboo: ['Quiet', 'Noise', 'Volume', 'Yell', 'Ears'] },
  { word: 'Snow', taboo: ['White', 'Cold', 'Winter', 'Flakes', 'Ice'] },
  { word: 'Ocean', taboo: ['Sea', 'Water', 'Waves', 'Fish', 'Salt'] },
  { word: 'Moon', taboo: ['Night', 'Sky', 'Full', 'Stars', 'Space'] },
  { word: 'Restaurant', taboo: ['Eat', 'Food', 'Menu', 'Waiter', 'Dinner'] },
  { word: 'Airport', taboo: ['Plane', 'Fly', 'Luggage', 'Gate', 'Travel'] },
  { word: 'Christmas', taboo: ['Santa', 'Tree', 'Presents', 'December', 'Holiday'] },
  { word: 'Halloween', taboo: ['Candy', 'Costume', 'October', 'Scary', 'Pumpkin'] },
  { word: 'Pool', taboo: ['Swim', 'Water', 'Dive', 'Summer', 'Deep'] },

  // ---- Around the house ----
  { word: 'Toaster', taboo: ['Bread', 'Kitchen', 'Pop', 'Burn', 'Breakfast'] },
  { word: 'Mirror', taboo: ['Reflection', 'Look', 'Glass', 'Bathroom', 'See'] },
  { word: 'Pillow', taboo: ['Sleep', 'Head', 'Bed', 'Soft', 'Fluff'] },
  { word: 'Towel', taboo: ['Dry', 'Shower', 'Beach', 'Wet', 'Cloth'] },
  { word: 'Soap', taboo: ['Wash', 'Bubbles', 'Clean', 'Hands', 'Bar'] },
  { word: 'Clock', taboo: ['Time', 'Hands', 'Tick', 'Wall', 'Hour'] },
  { word: 'Ladder', taboo: ['Climb', 'Steps', 'Tall', 'Reach', 'Rungs'] },
  { word: 'Hammer', taboo: ['Nail', 'Tool', 'Hit', 'Build', 'Thumb'] },
  { word: 'Scissors', taboo: ['Cut', 'Paper', 'Sharp', 'Blades', 'Snip'] },
  { word: 'Glue', taboo: ['Stick', 'Paste', 'Bond', 'Craft', 'Bottle'] },
  { word: 'Pencil', taboo: ['Write', 'Lead', 'Eraser', 'Sharpen', 'Paper'] },
  { word: 'Eraser', taboo: ['Mistake', 'Rub', 'Pencil', 'Gone', 'Pink'] },
  { word: 'Garden', taboo: ['Plants', 'Dirt', 'Grow', 'Vegetables', 'Water'] },
  { word: 'Fence', taboo: ['Yard', 'Gate', 'Neighbor', 'Wood', 'Around'] },
  { word: 'Mailbox', taboo: ['Letters', 'Mail', 'Post', 'Flag', 'Curb'] },
  { word: 'Doorbell', taboo: ['Ring', 'Visitor', 'Press', 'Door', 'Chime'] },
  { word: 'Basement', taboo: ['Downstairs', 'Underground', 'Dark', 'House', 'Storage'] },
  { word: 'Attic', taboo: ['Upstairs', 'Roof', 'Storage', 'Dusty', 'Boxes'] },
  { word: 'Garage', taboo: ['Car', 'Park', 'Door', 'Tools', 'House'] },
  { word: 'Elevator', taboo: ['Floors', 'Button', 'Up', 'Building', 'Ride'] },
  { word: 'Doorknob', taboo: ['Turn', 'Open', 'Door', 'Handle', 'Round'] },
  { word: 'Trash Can', taboo: ['Garbage', 'Throw', 'Lid', 'Bag', 'Smell'] },
  { word: 'Broom', taboo: ['Sweep', 'Floor', 'Bristles', 'Handle', 'Witch'] },
  { word: 'Bucket', taboo: ['Water', 'Handle', 'Carry', 'Fill', 'Mop'] },
  { word: 'Sponge', taboo: ['Wash', 'Dishes', 'Soak', 'Holes', 'Squeeze'] },
  { word: 'Laundry', taboo: ['Wash', 'Clothes', 'Dryer', 'Fold', 'Basket'] },
  { word: 'Dishwasher', taboo: ['Dishes', 'Clean', 'Kitchen', 'Load', 'Machine'] },
  { word: 'Oven', taboo: ['Bake', 'Hot', 'Kitchen', 'Cook', 'Stove'] },

  // ---- Food and drink ----
  { word: 'Salt', taboo: ['Pepper', 'Season', 'Shaker', 'Taste', 'Ocean'] },
  { word: 'Pepper', taboo: ['Salt', 'Season', 'Spicy', 'Sneeze', 'Grind'] },
  { word: 'Sugar', taboo: ['Sweet', 'Coffee', 'Spoon', 'White', 'Candy'] },
  { word: 'Honey', taboo: ['Bee', 'Sweet', 'Sticky', 'Jar', 'Golden'] },
  { word: 'Butter', taboo: ['Toast', 'Spread', 'Yellow', 'Stick', 'Melt'] },
  { word: 'Bacon', taboo: ['Pig', 'Breakfast', 'Crispy', 'Strips', 'Fry'] },
  { word: 'Cereal', taboo: ['Milk', 'Bowl', 'Breakfast', 'Box', 'Crunch'] },
  { word: 'Soup', taboo: ['Bowl', 'Spoon', 'Hot', 'Broth', 'Chicken'] },
  { word: 'Salad', taboo: ['Lettuce', 'Vegetables', 'Bowl', 'Dressing', 'Healthy'] },
  { word: 'Noodles', taboo: ['Pasta', 'Spaghetti', 'Boil', 'Slurp', 'Bowl'] },
  { word: 'Rice', taboo: ['Grain', 'White', 'Bowl', 'Cook', 'Sticky'] },
  { word: 'Taco', taboo: ['Shell', 'Mexican', 'Meat', 'Fold', 'Tuesday'] },
  { word: 'Sushi', taboo: ['Fish', 'Rice', 'Japanese', 'Roll', 'Chopsticks'] },
  { word: 'Barbecue', taboo: ['Grill', 'Meat', 'Smoke', 'Backyard', 'Sauce'] },
  { word: 'Picnic', taboo: ['Blanket', 'Park', 'Basket', 'Outside', 'Ants'] },
  { word: 'Cupcake', taboo: ['Frosting', 'Small', 'Bake', 'Wrapper', 'Sweet'] },
  { word: 'Cookie', taboo: ['Chocolate Chip', 'Bake', 'Jar', 'Milk', 'Sweet'] },
  { word: 'Peanut Butter', taboo: ['Jelly', 'Sandwich', 'Sticky', 'Nuts', 'Spread'] },
  { word: 'Milkshake', taboo: ['Straw', 'Thick', 'Ice Cream', 'Blend', 'Cup'] },
  { word: 'Straw', taboo: ['Drink', 'Sip', 'Plastic', 'Cup', 'Bend'] },
  { word: 'Napkin', taboo: ['Wipe', 'Table', 'Paper', 'Mouth', 'Lap'] },
  { word: 'Fork', taboo: ['Spoon', 'Eat', 'Prongs', 'Utensil', 'Stab'] },
  { word: 'Plate', taboo: ['Dish', 'Food', 'Round', 'Table', 'Wash'] },
  { word: 'Mug', taboo: ['Coffee', 'Handle', 'Cup', 'Hot', 'Drink'] },
  { word: 'Coffee', taboo: ['Beans', 'Morning', 'Cup', 'Caffeine', 'Brew'] },
  { word: 'Tea', taboo: ['Bag', 'Hot', 'Cup', 'Leaves', 'Brew'] },
  { word: 'Juice', taboo: ['Orange', 'Drink', 'Squeeze', 'Fruit', 'Glass'] },
  { word: 'Soda', taboo: ['Fizz', 'Can', 'Sweet', 'Bubbles', 'Pop'] },
  { word: 'Leftovers', taboo: ['Fridge', 'Food', 'Yesterday', 'Reheat', 'Container'] },
  { word: 'Buffet', taboo: ['All You Can Eat', 'Line', 'Plate', 'Food', 'Refill'] },
  { word: 'Food Truck', taboo: ['Street', 'Order', 'Wheels', 'Lunch', 'Window'] },
  { word: 'Drive-Thru', taboo: ['Window', 'Order', 'Car', 'Fast Food', 'Speaker'] },
  { word: 'Bakery', taboo: ['Bread', 'Cake', 'Shop', 'Oven', 'Sweet'] },

  // ---- Out and about ----
  { word: 'Hotel', taboo: ['Room', 'Stay', 'Travel', 'Bed', 'Check In'] },
  { word: 'Shopping Cart', taboo: ['Store', 'Wheels', 'Push', 'Groceries', 'Aisle'] },
  { word: 'Receipt', taboo: ['Store', 'Paper', 'Proof', 'Purchase', 'Return'] },
  { word: 'Wallet', taboo: ['Money', 'Pocket', 'Cards', 'Leather', 'Lost'] },
  { word: 'Piggy Bank', taboo: ['Coins', 'Save', 'Pink', 'Break', 'Savings'] },
  { word: 'Traffic Jam', taboo: ['Cars', 'Stuck', 'Slow', 'Road', 'Honk'] },
  { word: 'Speed Bump', taboo: ['Slow', 'Road', 'Car', 'Hump', 'Drive'] },
  { word: 'Movie Theater', taboo: ['Screen', 'Popcorn', 'Seats', 'Film', 'Dark'] },
  { word: 'Ticket', taboo: ['Admit', 'Show', 'Buy', 'Stub', 'Entry'] },
  { word: 'Stadium', taboo: ['Crowd', 'Seats', 'Game', 'Big', 'Field'] },

  // ---- Wearing ----
  { word: 'Sunglasses', taboo: ['Eyes', 'Sun', 'Shade', 'Wear', 'Cool'] },
  { word: 'Socks', taboo: ['Feet', 'Shoes', 'Pair', 'Wear', 'Drawer'] },
  { word: 'Gloves', taboo: ['Hands', 'Winter', 'Warm', 'Fingers', 'Pair'] },
  { word: 'Scarf', taboo: ['Neck', 'Winter', 'Wrap', 'Warm', 'Knit'] },
  { word: 'Jacket', taboo: ['Coat', 'Wear', 'Zipper', 'Cold', 'Sleeves'] },
  { word: 'Belt', taboo: ['Waist', 'Pants', 'Buckle', 'Hold', 'Leather'] },
  { word: 'Pocket', taboo: ['Pants', 'Hold', 'Hands', 'Keys', 'Inside'] },

  // ---- Body and noises ----
  { word: 'Shampoo', taboo: ['Hair', 'Wash', 'Bottle', 'Suds', 'Shower'] },
  { word: 'Razor', taboo: ['Shave', 'Sharp', 'Face', 'Blade', 'Cut'] },
  { word: 'Bandage', taboo: ['Cut', 'Wound', 'Stick', 'Heal', 'Scrape'] },
  { word: 'Thermometer', taboo: ['Temperature', 'Fever', 'Degrees', 'Mouth', 'Read'] },
  { word: 'Medicine', taboo: ['Pill', 'Sick', 'Doctor', 'Take', 'Cure'] },
  { word: 'Braces', taboo: ['Teeth', 'Metal', 'Straight', 'Orthodontist', 'Smile'] },
  { word: 'Freckles', taboo: ['Spots', 'Face', 'Sun', 'Skin', 'Nose'] },
  { word: 'Elbow', taboo: ['Arm', 'Bend', 'Joint', 'Point', 'Funny Bone'] },
  { word: 'Knee', taboo: ['Leg', 'Bend', 'Joint', 'Cap', 'Scrape'] },
  { word: 'Thumb', taboo: ['Finger', 'Hand', 'Up', 'Green', 'Sore'] },
  { word: 'Tongue', taboo: ['Mouth', 'Taste', 'Lick', 'Stick Out', 'Pink'] },
  { word: 'Eyebrow', taboo: ['Face', 'Hair', 'Eyes', 'Raise', 'Above'] },
  { word: 'Belly Button', taboo: ['Stomach', 'Navel', 'Lint', 'Middle', 'Innie'] },
  { word: 'Sneeze', taboo: ['Achoo', 'Nose', 'Bless You', 'Cover', 'Tissue'] },
  { word: 'Yawn', taboo: ['Tired', 'Mouth', 'Sleepy', 'Contagious', 'Open'] },
  { word: 'Snore', taboo: ['Sleep', 'Loud', 'Nose', 'Noise', 'Bed'] },
  { word: 'Burp', taboo: ['Gas', 'Mouth', 'Excuse Me', 'Loud', 'Soda'] },
  { word: 'Tickle', taboo: ['Laugh', 'Feather', 'Ribs', 'Squirm', 'Stop'] },
  { word: 'Hug', taboo: ['Arms', 'Squeeze', 'Embrace', 'Warm', 'Love'] },
  { word: 'Handshake', taboo: ['Hands', 'Greet', 'Meet', 'Firm', 'Deal'] },
  { word: 'High Five', taboo: ['Hands', 'Slap', 'Celebrate', 'Palm', 'Air'] },

  // ---- Screens and gadgets ----
  { word: 'Selfie', taboo: ['Photo', 'Phone', 'Face', 'Camera', 'Front'] },
  { word: 'Emoji', taboo: ['Text', 'Smiley', 'Face', 'Phone', 'Symbol'] },
  { word: 'Password', taboo: ['Login', 'Secret', 'Forget', 'Account', 'Type'] },
  { word: 'Wi-Fi', taboo: ['Internet', 'Signal', 'Router', 'Connect', 'Password'] },
  { word: 'Charger', taboo: ['Battery', 'Plug', 'Phone', 'Cord', 'Power'] },
  { word: 'Headphones', taboo: ['Ears', 'Music', 'Listen', 'Wires', 'Sound'] },
  { word: 'Remote Control', taboo: ['TV', 'Buttons', 'Channel', 'Couch', 'Lost'] },
  { word: 'Television', taboo: ['Watch', 'Screen', 'Shows', 'Remote', 'Channel'] },
  { word: 'Video Game', taboo: ['Console', 'Controller', 'Play', 'Screen', 'Level'] },
  { word: 'Cartoon', taboo: ['Animated', 'Kids', 'Draw', 'Saturday', 'Show'] },
  { word: 'Autocorrect', taboo: ['Phone', 'Typing', 'Wrong', 'Text', 'Change'] },
  { word: 'Group Chat', taboo: ['Text', 'Friends', 'Phone', 'Messages', 'Mute'] },

  // ---- Sport and games ----
  { word: 'Referee', taboo: ['Whistle', 'Rules', 'Game', 'Call', 'Stripes'] },
  { word: 'Trophy', taboo: ['Win', 'Gold', 'Award', 'Shelf', 'Champion'] },
  { word: 'Medal', taboo: ['Gold', 'Neck', 'Win', 'Olympics', 'Award'] },
  { word: 'Marathon', taboo: ['Run', 'Miles', 'Race', 'Long', 'Finish'] },
  { word: 'Soccer', taboo: ['Ball', 'Kick', 'Goal', 'Field', 'World Cup'] },
  { word: 'Baseball', taboo: ['Bat', 'Pitch', 'Diamond', 'Innings', 'Glove'] },
  { word: 'Football', taboo: ['Touchdown', 'Helmet', 'Field', 'Throw', 'Yards'] },
  { word: 'Tennis', taboo: ['Racket', 'Net', 'Serve', 'Court', 'Ball'] },
  { word: 'Golf', taboo: ['Clubs', 'Hole', 'Course', 'Swing', 'Putt'] },
  { word: 'Hockey', taboo: ['Puck', 'Ice', 'Stick', 'Goal', 'Skates'] },
  { word: 'Volleyball', taboo: ['Net', 'Spike', 'Serve', 'Court', 'Ball'] },
  { word: 'Ping Pong', taboo: ['Paddle', 'Table', 'Net', 'Bounce', 'Small'] },
  { word: 'Chess', taboo: ['Board', 'King', 'Pieces', 'Checkmate', 'Strategy'] },
  { word: 'Checkers', taboo: ['Board', 'Red', 'Black', 'Jump', 'King'] },
  { word: 'Dice', taboo: ['Roll', 'Six', 'Cubes', 'Game', 'Luck'] },
  { word: 'Board Game', taboo: ['Play', 'Pieces', 'Table', 'Family', 'Rules'] },
  { word: 'Hide and Seek', taboo: ['Count', 'Find', 'Hiding', 'Seek', 'Kids'] },
  { word: 'Jump Rope', taboo: ['Skip', 'Turn', 'Rope', 'Playground', 'Jump'] },

  // ---- School and playground ----
  { word: 'Slide', taboo: ['Playground', 'Down', 'Ladder', 'Slippery', 'Kids'] },
  { word: 'Swing', taboo: ['Push', 'Playground', 'Back and Forth', 'Chains', 'Seat'] },
  { word: 'Seesaw', taboo: ['Up and Down', 'Two', 'Playground', 'Balance', 'Board'] },
  { word: 'Sandbox', taboo: ['Sand', 'Toys', 'Kids', 'Dig', 'Playground'] },
  { word: 'Playground', taboo: ['Kids', 'Slide', 'Swings', 'Park', 'Recess'] },
  { word: 'Kindergarten', taboo: ['School', 'Young', 'First', 'Class', 'Nap'] },
  { word: 'Principal', taboo: ['School', 'Office', 'Boss', 'Trouble', 'Teacher'] },
  { word: 'Chalkboard', taboo: ['Write', 'School', 'Erase', 'Dust', 'Green'] },
  { word: 'Locker', taboo: ['School', 'Combination', 'Metal', 'Hallway', 'Books'] },
  { word: 'Report Card', taboo: ['Grades', 'School', 'Parents', 'Letters', 'Semester'] },
  { word: 'Field Trip', taboo: ['Bus', 'School', 'Museum', 'Permission', 'Class'] },
  { word: 'Cafeteria', taboo: ['Lunch', 'School', 'Tray', 'Tables', 'Food'] },
  { word: 'Janitor', taboo: ['Clean', 'School', 'Mop', 'Keys', 'Building'] },

  // ---- Farm and animals ----
  { word: 'Farmer', taboo: ['Crops', 'Tractor', 'Field', 'Barn', 'Grow'] },
  { word: 'Barn', taboo: ['Red', 'Farm', 'Animals', 'Hay', 'Doors'] },
  { word: 'Tractor', taboo: ['Farm', 'Drive', 'Plow', 'Wheels', 'Field'] },
  { word: 'Cow', taboo: ['Milk', 'Moo', 'Farm', 'Spots', 'Beef'] },
  { word: 'Chicken', taboo: ['Eggs', 'Cluck', 'Farm', 'Wings', 'Coop'] },
  { word: 'Pig', taboo: ['Oink', 'Mud', 'Farm', 'Pink', 'Bacon'] },
  { word: 'Horse', taboo: ['Ride', 'Saddle', 'Neigh', 'Stable', 'Gallop'] },
  { word: 'Sheep', taboo: ['Wool', 'Baa', 'Flock', 'Farm', 'Shear'] },
  { word: 'Goat', taboo: ['Beard', 'Butt', 'Farm', 'Milk', 'Climb'] },
  { word: 'Duck', taboo: ['Quack', 'Pond', 'Waddle', 'Feathers', 'Bread'] },
  { word: 'Turkey', taboo: ['Thanksgiving', 'Gobble', 'Bird', 'Feast', 'Feathers'] },
  { word: 'Rooster', taboo: ['Crow', 'Morning', 'Farm', 'Comb', 'Male'] },
  { word: 'Bee', taboo: ['Sting', 'Honey', 'Buzz', 'Hive', 'Flowers'] },
  { word: 'Butterfly', taboo: ['Wings', 'Caterpillar', 'Flutter', 'Colorful', 'Cocoon'] },
  { word: 'Ant', taboo: ['Small', 'Colony', 'Picnic', 'Hill', 'Crawl'] },
  { word: 'Worm', taboo: ['Dirt', 'Wiggle', 'Bait', 'Long', 'Ground'] },
  { word: 'Frog', taboo: ['Hop', 'Green', 'Pond', 'Ribbit', 'Lily Pad'] },
  { word: 'Turtle', taboo: ['Shell', 'Slow', 'Green', 'Hide', 'Pond'] },
  { word: 'Snake', taboo: ['Slither', 'Hiss', 'Long', 'Venom', 'Reptile'] },
  { word: 'Lizard', taboo: ['Reptile', 'Scales', 'Tail', 'Sun', 'Crawl'] },
  { word: 'Shark', taboo: ['Fin', 'Teeth', 'Ocean', 'Jaws', 'Bite'] },
  { word: 'Whale', taboo: ['Big', 'Ocean', 'Blowhole', 'Blue', 'Mammal'] },
  { word: 'Dolphin', taboo: ['Ocean', 'Smart', 'Flipper', 'Jump', 'Squeak'] },
  { word: 'Crab', taboo: ['Claws', 'Beach', 'Sideways', 'Shell', 'Pinch'] },
  { word: 'Starfish', taboo: ['Ocean', 'Five', 'Arms', 'Beach', 'Sea'] },
  { word: 'Seagull', taboo: ['Beach', 'Bird', 'Squawk', 'Fries', 'Fly'] },
  { word: 'Owl', taboo: ['Hoot', 'Night', 'Wise', 'Bird', 'Eyes'] },
  { word: 'Eagle', taboo: ['Bird', 'Bald', 'Fly', 'Talons', 'America'] },
  { word: 'Parrot', taboo: ['Talk', 'Colorful', 'Bird', 'Repeat', 'Pirate'] },
  { word: 'Squirrel', taboo: ['Nuts', 'Tree', 'Bushy', 'Tail', 'Acorn'] },
  { word: 'Rabbit', taboo: ['Hop', 'Ears', 'Carrot', 'Bunny', 'Fluffy'] },
  { word: 'Deer', taboo: ['Antlers', 'Forest', 'Bambi', 'Run', 'Spots'] },
  { word: 'Fox', taboo: ['Red', 'Sly', 'Tail', 'Forest', 'Cunning'] },
  { word: 'Wolf', taboo: ['Howl', 'Pack', 'Moon', 'Wild', 'Dog'] },
  { word: 'Monkey', taboo: ['Banana', 'Tree', 'Swing', 'Tail', 'Jungle'] },
  { word: 'Zebra', taboo: ['Stripes', 'Africa', 'Horse', 'Black', 'White'] },
  { word: 'Hippo', taboo: ['Big', 'Water', 'Africa', 'Mouth', 'Heavy'] },
  { word: 'Camel', taboo: ['Hump', 'Desert', 'Ride', 'Sand', 'Spit'] },
  { word: 'Panda', taboo: ['Bamboo', 'China', 'Black', 'White', 'Cute'] },

  // ---- The funny ones ----
  { word: 'Wedgie', taboo: ['Underwear', 'Pull', 'Prank', 'Embarrass', 'Up'] },
  { word: 'Bad Hair Day', taboo: ['Messy', 'Morning', 'Mirror', 'Frizzy', 'Hat'] },
  { word: 'Brain Freeze', taboo: ['Cold', 'Ice Cream', 'Head', 'Fast', 'Ouch'] },
  { word: 'Awkward Silence', taboo: ['Quiet', 'Uncomfortable', 'Pause', 'Room', 'Nobody'] },
  { word: 'Dad Joke', taboo: ['Pun', 'Groan', 'Corny', 'Father', 'Funny'] },
  { word: 'Snooze Button', taboo: ['Alarm', 'Morning', 'Press', 'Sleep', 'Again'] },
  { word: 'Sock Puppet', taboo: ['Hand', 'Googly Eyes', 'Show', 'Talk', 'Craft'] },
  { word: 'Whoopee Cushion', taboo: ['Prank', 'Sit', 'Noise', 'Air', 'Chair'] },
  { word: 'Banana Peel', taboo: ['Slip', 'Fall', 'Yellow', 'Ground', 'Cartoon'] },
  { word: 'Clown', taboo: ['Circus', 'Nose', 'Makeup', 'Balloons', 'Scary'] },
  { word: 'Mime', taboo: ['Silent', 'Invisible Wall', 'White Face', 'Gestures', 'Street'] },
  { word: 'Pinata', taboo: ['Candy', 'Stick', 'Blindfold', 'Hit', 'Party'] },
  { word: 'Confetti', taboo: ['Throw', 'Paper', 'Celebrate', 'Colorful', 'Mess'] },
  { word: 'Toilet Paper', taboo: ['Roll', 'Bathroom', 'Wipe', 'Soft', 'Out'] },
  { word: 'Plunger', taboo: ['Toilet', 'Clog', 'Rubber', 'Push', 'Bathroom'] },
  { word: 'Bubble Wrap', taboo: ['Pop', 'Package', 'Plastic', 'Fun', 'Protect'] },
  { word: 'Sticky Note', taboo: ['Yellow', 'Remind', 'Stick', 'Small', 'Desk'] },
  { word: 'Paper Cut', taboo: ['Small', 'Ouch', 'Finger', 'Sting', 'Edge'] },
  { word: 'Couch Potato', taboo: ['Lazy', 'TV', 'Sit', 'Snacks', 'All Day'] },
];
