/**
 * Taboo card deck. Each card has one Guess Word and five Taboo (forbidden) words.
 * Family-friendly set for reunion play.
 */

export interface TabooCard {
  word: string;
  taboo: [string, string, string, string, string];
}

export const TABOO_CARDS: TabooCard[] = [
  { word: 'Birthday', taboo: ['Cake', 'Party', 'Candles', 'Age', 'Celebrate'] },
  { word: 'Beach', taboo: ['Sand', 'Ocean', 'Sun', 'Towel', 'Wave'] },
  { word: 'Pizza', taboo: ['Cheese', 'Pepperoni', 'Slice', 'Italian', 'Crust'] },
  { word: 'Snowman', taboo: ['Frosty', 'Winter', 'Carrot', 'Cold', 'Build'] },
  { word: 'Library', taboo: ['Books', 'Quiet', 'Read', 'Borrow', 'Shelves'] },
  { word: 'Campfire', taboo: ['Marshmallow', 'Wood', 'Flame', 'Smoke', 'Camping'] },
  { word: 'Dentist', taboo: ['Teeth', 'Drill', 'Cavity', 'Doctor', 'Floss'] },
  { word: 'Rainbow', taboo: ['Colors', 'Rain', 'Sky', 'Arc', 'Pot of Gold'] },
  { word: 'Elephant', taboo: ['Trunk', 'Big', 'Gray', 'Tusks', 'Africa'] },
  { word: 'Basketball', taboo: ['Hoop', 'Dribble', 'Court', 'NBA', 'Shoot'] },
  { word: 'Umbrella', taboo: ['Rain', 'Wet', 'Open', 'Handle', 'Cover'] },
  { word: 'Popcorn', taboo: ['Movie', 'Butter', 'Kernel', 'Pop', 'Snack'] },
  { word: 'Astronaut', taboo: ['Space', 'NASA', 'Rocket', 'Moon', 'Suit'] },
  { word: 'Piano', taboo: ['Keys', 'Music', 'Play', 'Instrument', 'Black and White'] },
  { word: 'Sandwich', taboo: ['Bread', 'Lunch', 'Meat', 'Peanut Butter', 'Sub'] },
  { word: 'Firefighter', taboo: ['Fire', 'Truck', 'Hose', 'Ladder', 'Rescue'] },
  { word: 'Roller Coaster', taboo: ['Ride', 'Amusement Park', 'Fast', 'Loop', 'Scream'] },
  { word: 'Toothbrush', taboo: ['Teeth', 'Paste', 'Clean', 'Bristles', 'Mouth'] },
  { word: 'Kangaroo', taboo: ['Australia', 'Hop', 'Pouch', 'Joey', 'Jump'] },
  { word: 'Chocolate', taboo: ['Candy', 'Sweet', 'Brown', 'Cocoa', 'Bar'] },
  { word: 'Airplane', taboo: ['Fly', 'Pilot', 'Wings', 'Airport', 'Sky'] },
  { word: 'Vampire', taboo: ['Blood', 'Dracula', 'Fangs', 'Bat', 'Bite'] },
  { word: 'Guitar', taboo: ['Strings', 'Play', 'Music', 'Rock', 'Strum'] },
  { word: 'Bowling', taboo: ['Pins', 'Strike', 'Ball', 'Alley', 'Roll'] },
  { word: 'Pancake', taboo: ['Syrup', 'Breakfast', 'Flip', 'Flat', 'Batter'] },
  { word: 'Spider', taboo: ['Web', 'Eight', 'Legs', 'Insect', 'Crawl'] },
  { word: 'Sunburn', taboo: ['Red', 'Beach', 'Lotion', 'Skin', 'Hot'] },
  { word: 'Wedding', taboo: ['Bride', 'Groom', 'Marriage', 'Ring', 'Dress'] },
  { word: 'Refrigerator', taboo: ['Cold', 'Food', 'Kitchen', 'Freezer', 'Ice'] },
  { word: 'Skateboard', taboo: ['Wheels', 'Ride', 'Trick', 'Ramp', 'Deck'] },
  { word: 'Cowboy', taboo: ['Horse', 'Hat', 'West', 'Lasso', 'Boots'] },
  { word: 'Igloo', taboo: ['Ice', 'Eskimo', 'Cold', 'House', 'Snow'] },
  { word: 'Lemonade', taboo: ['Drink', 'Sour', 'Stand', 'Yellow', 'Summer'] },
  { word: 'Pirate', taboo: ['Ship', 'Treasure', 'Eye Patch', 'Parrot', 'Arr'] },
  { word: 'Trampoline', taboo: ['Jump', 'Bounce', 'Springs', 'Backyard', 'Flip'] },
  { word: 'Volcano', taboo: ['Lava', 'Erupt', 'Mountain', 'Hot', 'Ash'] },
  { word: 'Waffle', taboo: ['Breakfast', 'Syrup', 'Squares', 'Iron', 'Pancake'] },
  { word: 'Zookeeper', taboo: ['Animals', 'Cage', 'Feed', 'Zoo', 'Lion'] },
  { word: 'Fireworks', taboo: ['Fourth of July', 'Explode', 'Sky', 'Boom', 'Colors'] },
  { word: 'Mermaid', taboo: ['Fish', 'Tail', 'Ocean', 'Ariel', 'Swim'] },
  { word: 'Microwave', taboo: ['Heat', 'Oven', 'Popcorn', 'Kitchen', 'Minutes'] },
  { word: 'Ballet', taboo: ['Dance', 'Tutu', 'Toes', 'Swan', 'Graceful'] },
  { word: 'Hamburger', taboo: ['Bun', 'Beef', 'Fries', 'McDonald’s', 'Patty'] },
  { word: 'Scarecrow', taboo: ['Birds', 'Field', 'Straw', 'Farm', 'Corn'] },
  { word: 'Submarine', taboo: ['Underwater', 'Ship', 'Ocean', 'Navy', 'Periscope'] },
  { word: 'Tornado', taboo: ['Wind', 'Storm', 'Spin', 'Twister', 'Funnel'] },
  { word: 'Giraffe', taboo: ['Neck', 'Tall', 'Spots', 'Africa', 'Animal'] },
  { word: 'Karate', taboo: ['Kick', 'Belt', 'Chop', 'Martial Arts', 'Punch'] },
  { word: 'Lighthouse', taboo: ['Ocean', 'Light', 'Ships', 'Tower', 'Coast'] },
  { word: 'Marshmallow', taboo: ['Campfire', 'Roast', 'White', 'Soft', 'S’more'] },
  { word: 'Ninja', taboo: ['Sword', 'Sneak', 'Black', 'Japan', 'Turtle'] },
  { word: 'Octopus', taboo: ['Eight', 'Tentacles', 'Ocean', 'Ink', 'Arms'] },
  { word: 'Parachute', taboo: ['Jump', 'Plane', 'Sky', 'Fall', 'Open'] },
  { word: 'Quicksand', taboo: ['Sink', 'Stuck', 'Sand', 'Jungle', 'Trap'] },
  { word: 'Robot', taboo: ['Machine', 'Metal', 'Beep', 'Computer', 'Future'] },
  { word: 'Sledding', taboo: ['Snow', 'Hill', 'Winter', 'Slide', 'Downhill'] },
  { word: 'Telescope', taboo: ['Stars', 'Look', 'Space', 'Lens', 'Astronomy'] },
  { word: 'Unicorn', taboo: ['Horn', 'Horse', 'Magic', 'Rainbow', 'Mythical'] },
  { word: 'Vacuum', taboo: ['Clean', 'Carpet', 'Suck', 'Dirt', 'Floor'] },
  { word: 'Waterfall', taboo: ['River', 'Niagara', 'Splash', 'Rocks', 'Flow'] },
  { word: 'X-ray', taboo: ['Bones', 'Doctor', 'Picture', 'Hospital', 'See Through'] },
  { word: 'Yo-yo', taboo: ['String', 'Up and Down', 'Toy', 'Spin', 'Trick'] },
  { word: 'Zipper', taboo: ['Jacket', 'Pants', 'Up', 'Teeth', 'Close'] },
  { word: 'Alarm Clock', taboo: ['Wake', 'Morning', 'Ring', 'Snooze', 'Time'] },
  { word: 'Babysitter', taboo: ['Kids', 'Watch', 'Parents', 'Pay', 'Night'] },
  { word: 'Cactus', taboo: ['Desert', 'Prickly', 'Needles', 'Green', 'Plant'] },
  { word: 'Dinosaur', taboo: ['Extinct', 'T-Rex', 'Fossil', 'Jurassic', 'Reptile'] },
  { word: 'Earthquake', taboo: ['Shake', 'Ground', 'Fault', 'Richter', 'Tremor'] },
  { word: 'Ferris Wheel', taboo: ['Ride', 'Carnival', 'Circle', 'Tall', 'Seats'] },
  { word: 'Garage Sale', taboo: ['Sell', 'Yard', 'Stuff', 'Cheap', 'Saturday'] },
  { word: 'Hiccups', taboo: ['Scare', 'Water', 'Breath', 'Sound', 'Stop'] },
  { word: 'Ice Cream', taboo: ['Cone', 'Cold', 'Scoop', 'Flavor', 'Dessert'] },
  { word: 'Jellyfish', taboo: ['Sting', 'Ocean', 'Tentacles', 'Float', 'Clear'] },
  { word: 'Ketchup', taboo: ['Tomato', 'Fries', 'Red', 'Mustard', 'Bottle'] },
  { word: 'Lawn Mower', taboo: ['Grass', 'Cut', 'Yard', 'Push', 'Engine'] },
  { word: 'Magician', taboo: ['Trick', 'Rabbit', 'Hat', 'Wand', 'Abracadabra'] },
  { word: 'Nightmare', taboo: ['Dream', 'Scary', 'Sleep', 'Wake', 'Bad'] },
  { word: 'Orchestra', taboo: ['Music', 'Instruments', 'Conductor', 'Symphony', 'Violin'] },
  { word: 'Penguin', taboo: ['Antarctica', 'Bird', 'Waddle', 'Tuxedo', 'Ice'] },
  { word: 'Quilt', taboo: ['Blanket', 'Sew', 'Patches', 'Bed', 'Grandma'] },
  { word: 'Recess', taboo: ['School', 'Play', 'Break', 'Playground', 'Kids'] },
  { word: 'Seatbelt', taboo: ['Car', 'Safety', 'Buckle', 'Strap', 'Click'] },
  { word: 'Treehouse', taboo: ['Climb', 'Kids', 'Wood', 'Backyard', 'Ladder'] },
  { word: 'Uniform', taboo: ['Clothes', 'School', 'Wear', 'Same', 'Team'] },
  { word: 'Ventriloquist', taboo: ['Dummy', 'Voice', 'Puppet', 'Mouth', 'Talk'] },
  { word: 'Windmill', taboo: ['Wind', 'Blades', 'Spin', 'Holland', 'Farm'] },
  { word: 'Yearbook', taboo: ['School', 'Photos', 'Sign', 'Memories', 'Graduation'] },
  { word: 'Aquarium', taboo: ['Fish', 'Tank', 'Water', 'Glass', 'Visit'] },
  { word: 'Bubble Gum', taboo: ['Chew', 'Blow', 'Pink', 'Sticky', 'Pop'] },
  { word: 'Carpool', taboo: ['Drive', 'Share', 'Ride', 'Work', 'Lane'] },
  { word: 'Detective', taboo: ['Clues', 'Mystery', 'Solve', 'Sherlock', 'Case'] },
  { word: 'Escalator', taboo: ['Stairs', 'Moving', 'Mall', 'Up', 'Ride'] },
  { word: 'Fortune Cookie', taboo: ['Chinese', 'Message', 'Paper', 'Crack', 'Lucky'] },
  { word: 'Goosebumps', taboo: ['Cold', 'Scared', 'Skin', 'Chills', 'Arms'] },
  { word: 'Hopscotch', taboo: ['Jump', 'Chalk', 'Sidewalk', 'Squares', 'Game'] },
  { word: 'Inchworm', taboo: ['Crawl', 'Small', 'Measure', 'Green', 'Bug'] },
  { word: 'Juggler', taboo: ['Balls', 'Throw', 'Catch', 'Circus', 'Air'] },
  { word: 'Kayak', taboo: ['Paddle', 'Boat', 'River', 'Water', 'Canoe'] },
  { word: 'Leprechaun', taboo: ['Irish', 'Gold', 'Green', 'Lucky', 'Rainbow'] },
  { word: 'Mustache', taboo: ['Lip', 'Hair', 'Face', 'Shave', 'Beard'] },
  { word: 'Nest', taboo: ['Bird', 'Eggs', 'Tree', 'Twigs', 'Build'] },
  { word: 'Overalls', taboo: ['Pants', 'Straps', 'Farmer', 'Denim', 'Wear'] },
  { word: 'Puzzle', taboo: ['Pieces', 'Fit', 'Picture', 'Jigsaw', 'Solve'] },
  { word: 'Quarterback', taboo: ['Football', 'Throw', 'Pass', 'Team', 'Huddle'] },
  { word: 'Raccoon', taboo: ['Mask', 'Trash', 'Night', 'Animal', 'Stripes'] },
  { word: 'Snorkel', taboo: ['Breathe', 'Underwater', 'Mask', 'Tube', 'Swim'] },
  { word: 'Tugboat', taboo: ['Pull', 'Ship', 'Small', 'Harbor', 'Water'] },
  { word: 'Applause', taboo: ['Clap', 'Hands', 'Audience', 'Cheer', 'Bravo'] },
  { word: 'Backpack', taboo: ['School', 'Carry', 'Shoulders', 'Books', 'Bag'] },
  { word: 'Chameleon', taboo: ['Color', 'Change', 'Lizard', 'Blend', 'Camouflage'] },
  { word: 'Doughnut', taboo: ['Hole', 'Glazed', 'Sprinkles', 'Fried', 'Sweet'] },
  { word: 'Eclipse', taboo: ['Sun', 'Moon', 'Dark', 'Shadow', 'Sky'] },
  { word: 'Flamingo', taboo: ['Pink', 'Bird', 'One Leg', 'Stand', 'Lawn'] },
  { word: 'Gingerbread', taboo: ['Cookie', 'House', 'Man', 'Christmas', 'Candy'] },
  { word: 'Hammock', taboo: ['Swing', 'Trees', 'Relax', 'Nap', 'Rope'] },
  { word: 'Iceberg', taboo: ['Titanic', 'Ocean', 'Cold', 'Float', 'Tip'] },
  { word: 'Jackpot', taboo: ['Win', 'Money', 'Lottery', 'Slot Machine', 'Prize'] },
  { word: 'Kite', taboo: ['Fly', 'String', 'Wind', 'Sky', 'Tail'] },
  { word: 'Limousine', taboo: ['Long', 'Car', 'Driver', 'Fancy', 'Prom'] },
  { word: 'Muffin', taboo: ['Blueberry', 'Bake', 'Breakfast', 'Cupcake', 'Top'] },
  { word: 'Newspaper', taboo: ['Read', 'Headlines', 'Daily', 'Print', 'Deliver'] },
  { word: 'Ostrich', taboo: ['Bird', 'Big', 'Run', 'Head in Sand', 'Egg'] },
  { word: 'Pillow Fight', taboo: ['Hit', 'Feathers', 'Bed', 'Sleepover', 'Soft'] },
  { word: 'Quicksilver', taboo: ['Mercury', 'Fast', 'Metal', 'Liquid', 'Silver'] },
  { word: 'Rocking Chair', taboo: ['Sit', 'Back and Forth', 'Porch', 'Grandma', 'Wood'] },
  { word: 'Stethoscope', taboo: ['Doctor', 'Heart', 'Listen', 'Chest', 'Nurse'] },
  { word: 'Tricycle', taboo: ['Three', 'Wheels', 'Ride', 'Kid', 'Pedal'] },
  { word: 'Underdog', taboo: ['Win', 'Lose', 'Expected', 'Favorite', 'Root'] },
  { word: 'Violin', taboo: ['Strings', 'Bow', 'Music', 'Fiddle', 'Orchestra'] },
  { word: 'Wheelbarrow', taboo: ['Push', 'Garden', 'Wheel', 'Carry', 'Dirt'] },
  { word: 'Sunflower', taboo: ['Yellow', 'Seeds', 'Tall', 'Garden', 'Sun'] },
  { word: 'Time Machine', taboo: ['Travel', 'Past', 'Future', 'Back', 'Invention'] },
  { word: 'Superhero', taboo: ['Cape', 'Powers', 'Save', 'Comic', 'Villain'] },
  { word: 'Slippers', taboo: ['Feet', 'Cozy', 'House', 'Shoes', 'Wear'] },
  { word: 'Photograph', taboo: ['Camera', 'Picture', 'Smile', 'Album', 'Take'] },
  { word: 'Opera', taboo: ['Sing', 'Music', 'Stage', 'Loud', 'Fat Lady'] },
  { word: 'Mosquito', taboo: ['Bite', 'Itch', 'Bug', 'Blood', 'Buzz'] },
  { word: 'Lifeguard', taboo: ['Pool', 'Save', 'Whistle', 'Beach', 'Swim'] },
  { word: 'Karaoke', taboo: ['Sing', 'Microphone', 'Songs', 'Words', 'Screen'] },
  { word: 'Homework', taboo: ['School', 'Assignment', 'Teacher', 'Study', 'Due'] },
  { word: 'Grasshopper', taboo: ['Jump', 'Green', 'Insect', 'Legs', 'Field'] },
  { word: 'Fishing Rod', taboo: ['Catch', 'Reel', 'Bait', 'Hook', 'Lake'] },
  { word: 'Escalate', taboo: ['Increase', 'Rise', 'Grow', 'Up', 'Worse'] },
  { word: 'Drum', taboo: ['Beat', 'Sticks', 'Band', 'Hit', 'Rhythm'] },
  { word: 'Compass', taboo: ['North', 'Direction', 'Needle', 'Navigate', 'Lost'] },
  { word: 'Blender', taboo: ['Smoothie', 'Mix', 'Kitchen', 'Blade', 'Juice'] },
  { word: 'Avalanche', taboo: ['Snow', 'Mountain', 'Slide', 'Bury', 'Ski'] },
];
